services:
  app:
    build:
      context: .
    container_name: noteika-go-app
    networks:
      - noteika-network
      - proxy_net
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_net"
      
      # Routing
      - "traefik.http.routers.noteika.rule=Host(`noteika.com`)"
      - "traefik.http.routers.noteika.entrypoints=websecure"
      - "traefik.http.routers.noteika.tls.certresolver=myresolver"
      
      # Service definition
      - "traefik.http.routers.noteika.service=noteika-svc"
      - "traefik.http.services.noteika-svc.loadbalancer.server.port=8080"

networks:
  noteika-network:
    driver: bridge
    name: noteika-net
  proxy_net:
    external: true